services:
  # Development server with hot reload
  docusaurus-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.docusaurus
    environment:
      - NODE_ENV=development
    command: npm run start -- --host 0.0.0.0 --port 3000
    profiles:
      - dev

  # Production build and serve
  docusaurus-prod:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    profiles:
      - prod

  # Build only (for CI/CD testing)
  docusaurus-build:
    build:
      context: .
      target: builder
    volumes:
      - ./build:/app/build
    profiles:
      - build
