name: AI-Enhanced Release Notes
on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to generate release notes for'
        required: false
        default: 'latest'

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate AI Release Notes
        run: npx tsx scripts/ai-release-notes.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RELEASE_NOTES_MODEL: gpt-4
          RELEASE_STYLE: comprehensive
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: true
      
  publish:
    needs: generate-notes
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
