name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Debug environment
        run: |
          echo "=== Environment Debug ==="
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "TypeScript installed: $(npm list typescript --depth=0 || echo 'not found')"
          echo "Types installed: $(npm list @types/node @types/jest --depth=0 || echo 'not found')"
          echo "tsconfig.json exists: $(test -f tsconfig.json && echo 'yes' || echo 'no')"
          echo "eslint.config.js exists: $(test -f eslint.config.js && echo 'yes' || echo 'no')"
          echo "Makefile exists: $(test -f Makefile && echo 'yes' || echo 'no')"

      - name: Install dependencies
        run: |
          echo "=== Installing Dependencies ==="
          npm install
          echo "=== Verifying ESLint Installation ==="
          echo "ESLint version: $(npx eslint --version)"
          echo "ESLint config exists: $(test -f eslint.config.js && echo 'yes' || echo 'no')"

      - name: Run ESLint and TypeScript checks
        run: |
          echo "=== Running ESLint + TypeScript Checks ==="
          npm run lint
          echo "✅ ESLint and TypeScript checks completed successfully"

      - name: Check formatting
        run: |
          echo "=== Checking Code Formatting ==="
          if npm run format:check; then
            echo "✅ Code formatting is correct"
          else
            echo "⚠️ Code formatting issues found (non-blocking)"
            echo "Run 'npm run format' to fix formatting issues"
          fi
        continue-on-error: true
