name: Test MCP Server

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Try make install first
        if ! make install; then
          echo "❌ Make install failed, trying npm install..."
          npm install
        fi

    - name: Test Node.js compatibility
      run: |
        make node-compat
        echo "Testing server health check..."
        node dist/src/index.js --test

    - name: Run unit tests
      run: make test

    - name: Build the project
      run: npm run build

    - name: Test MCP server health check
      run: |
        echo "Testing MCP server health check..."
        if npm run health; then
          echo "✅ MCP server health check passed"
        else
          echo "❌ MCP server health check failed"
          exit 1
        fi

    - name: Test MCP server functionality
      run: |
        echo "Testing MCP server functionality..."

        # Use our validation script to check build output
        if [ -f "scripts/validate-build.js" ]; then
          echo "Running comprehensive build validation..."
          node scripts/validate-build.js
        fi

        # Check that the built server contains expected MCP tools
        echo "Checking for MCP tool implementations..."
        if grep -q "analyze_project" dist/src/index.js; then
          echo "✅ analyze_project tool found"
        else
          echo "❌ analyze_project tool not found"
          exit 1
        fi

        if grep -q "ListToolsRequestSchema" dist/src/index.js; then
          echo "✅ ListToolsRequestSchema handler found"
        else
          echo "❌ ListToolsRequestSchema handler not found"
          exit 1
        fi

        echo "✅ MCP server functionality validated"

    - name: Upload coverage reports
      if: matrix.node-version == '18'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false
